name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.yarnpkg.com

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
